### ISSUE TITLE
setup.py missing

### ISSUE THREAD

**Issue by psukys** [sirex/ubuntu.lt#4]
While trying to setup the project,  under given instructions in readme, `pip install .` returns

```
Directory '.' is not installable. File 'setup.py' not found.
```

**Comment by sirex** [comment]
Actually readme file and whole initial project layout is taken from [here](https://github.com/nitely/Spirit/tree/master/example) and does not match the reality.

Is this bug report is about incorrect readme file or this is a help request about how to set up project for development?

**Comment by psukys** [comment]
The intention was setting up the environment, either way it would be both.

**Comment by sirex** [comment]
In order to setup development environment run these commands:

```
$ git clone https://github.com/sirex/ubuntu.lt.git
$ cd ubuntu.lt
$ virtualenv -p /usr/bin/python3 venv
$ source venv/bin/activate
$ pip install -r requirements.txt
$ python manage.py spiritinstall
$ python manage.py runserver
```
